# Generated by Django 2.2 on 2019-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(default=9999999999),
        ),
    ]
