# Generated by Django 2.2.6 on 2019-11-16 10:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.IntegerField(blank=True, default=0, verbose_name=blog.models.Friend),
        ),
    ]
