# Generated by Django 2.2.6 on 2019-11-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191116_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_id',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
