# Generated by Django 2.2.6 on 2019-11-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
