# Generated by Django 2.2.6 on 2019-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191106_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
