# Generated by Django 2.2 on 2019-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
