# Generated by Django 2.2.6 on 2019-10-30 07:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/posts/'), upload_to=''),
        ),
    ]
