# Generated by Django 2.2.6 on 2019-11-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='videofile',
            new_name='video',
        ),
    ]
