# Generated by Django 2.2.6 on 2019-11-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191116_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_id',
        ),
    ]
