# Generated by Django 2.2.6 on 2019-11-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
    ]
