# Generated by Django 2.2.6 on 2019-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191028_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
