# Generated by Django 2.2.6 on 2019-11-02 10:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', storage=django.core.files.storage.FileSystemStorage(location='media/posts/'), upload_to=''),
        ),
    ]
