# Generated by Django 2.2.6 on 2019-11-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_friend_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('from_user', 'to_user')},
        ),
    ]
