# Generated by Django 2.2.7 on 2019-11-04 11:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', storage=django.core.files.storage.FileSystemStorage(location='media/posts/'), upload_to=''),
        ),
    ]
