# Generated by Django 2.2.6 on 2019-11-16 11:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191116_1606'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friend',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='to_user',
        ),
    ]
