# Generated by Django 2.2.6 on 2019-11-02 10:34

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191102_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_id',
            field=models.ManyToManyField(related_name='_user_friend_id_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', storage=django.core.files.storage.FileSystemStorage(location='posts/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(),
        ),
    ]
