# Generated by Django 2.2.6 on 2019-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191028_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='posts'),
        ),
    ]
