# Generated by Django 2.2.7 on 2019-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_posts_friend_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='likes',
            new_name='like',
        ),
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
