# Generated by Django 2.2.6 on 2019-11-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191101_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.DeleteModel(
            name='FriendMgmt',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
