# Generated by Django 2.2 on 2019-10-29 14:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191029_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/posts'), upload_to=''),
        ),
    ]
