# Generated by Django 2.2.6 on 2019-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191101_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
