# Generated by Django 2.2.7 on 2019-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
